on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Djamel HADDADI'
        myInput2: 'Wattrelos ville'
    - name: output the memory
      run: |
          echo ${{ steps.hello.outputs.memory }}
          echo ${{ steps.hello.outputs.cpu }}
          echo "total memory sucessfully output"
